FROM python:3.12.4

WORKDIR /Docker-deck

ENV PYTHONUNBUFFERED=1
ENV DOCKERDECK_GITHUB_KEY=<>

RUN apt-get update && apt-get -y install cron && apt-get install nano

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

ADD crontab /etc/cronjob
RUN crontab /etc/cronjob

COPY . .

CMD ["cron", "-f"]